project:
  type: book
  output-dir: docs

book:
  title: "frr"
  author: "Norah Jones"
  date: "12/3/2024"
  site-url: https://hyxicn.github.io/frr/
  repo-url: https://github.com/hyxicn/frr/
  repo-branch: main
  repo-actions: [edit]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  #pdf:
   # documentclass: scrreprt

